package com.benzenelabs.hydra.host.data.session

import java.util.UUID

/**
 * Opaque unique identifier for a [Session].
 *
 * A session is scoped to a (channelId, remoteId) pair. The [SessionId] is a UUID
 * generated by the host at session creation time.
 */
@JvmInline
value class SessionId(val value: String) {
    init {
        require(value.isNotBlank()) { "SessionId must not be blank" }
        UUID.fromString(value)
    }

    override fun toString(): String = value

    companion object {
        fun generate(): SessionId = SessionId(UUID.randomUUID().toString())
    }
}
